apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "6" # My account is limited to 6 load balancers
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: teastore
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080 
