apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: teastore-vert-1
spec:
  benchmark: teastore
  load:
    loadType: "NumUsers"
    loadValues: [1, 3, 5]
  resources:
    resourceType: "PodResources"
    resourceValues: [500, 1000, 1500, 2000, 2500]
  slos:
    - name: "uiLatency"
      properties:
        warmup: 600
        threshold: 200
  execution:
    strategy:
      name: "RestrictionSearch"
      restrictions:
        - "LowerBound"
      searchStrategy: "LinearSearch"
    duration: 600  # in seconds
    repetitions: 1
  configOverrides: []
