apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: teastore-vertical-1-lb
spec:
  benchmark: teastore
  load:
    loadType: "NumUsers"
    loadValues: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35]
  resources:
    resourceType: "PodResources"
    resourceValues: [500, 1000, 1500, 2000]
  slos:
    - name: "throughput"
      properties:
        warmup: 600
        thresholdFromExpression: "180 * L * 0.8"
  execution:
    strategy:
      name: "RestrictionSearch"
      restrictions:
        - "LowerBound"
      searchStrategy: "LinearSearch"
    duration: 1200  # in seconds
    repetitions: 1
  configOverrides: []
